---
driver:
  name: vagrant

platforms:
  - name: centos-6.5
  - name: centos-5.10
  - name: ubuntu-14.04
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[clamav_test]
    attributes:
  - name: all_options_enabled
    run_list:
      - recipe[clamav_test]
    attributes:
      clamav:
        clamd:
          enabled: true
          log_file: false
          log_syslog: yes
          log_facility: LOG_LOCAL7
        freshclam:
          enabled: true
          update_log_file: false
          log_syslog: yes
          log_facility: LOG_LOCAL7
        dev_package: true
        scan:
          script:
            enable: true
          minimal:
            enable: true
          full:
            enable: true
