# encoding: utf-8
# frozen_string_literal: true
#
# Cookbook Name:: clamav
# Library:: resource_clamav_config_debian
#
# Copyright 2012-2017, Jonathan Hartman
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

require_relative 'resource_clamav_config'

class Chef
  class Resource
    # A Debian implemenation of the ClamAV config resource. The default configs
    # installed by Ubuntu 16.04 look like (defaults that we can thus ignore are
    # marked):
    #
    # /etc/clamav/clamd.conf:
    #
    # #Automatically Generated by clamav-daemon postinst
    # #To reconfigure clamd run #dpkg-reconfigure clamav-daemon
    # #Please read /usr/share/doc/clamav-daemon/README.Debian.gz for details
    # LocalSocket /var/run/clamav/clamd.ctl
    # FixStaleSocket true # The ClamAV default
    # LocalSocketGroup clamav # The ClamAV default
    # LocalSocketMode 666 # The ClamAV default
    # # TemporaryDirectory is not set to its default /tmp here to make overriding
    # # the default with environment variables TMPDIR/TMP/TEMP possible
    # User clamav
    # AllowSupplementaryGroups false # The ClamAV default
    # ScanMail true # The ClamAV default
    # ScanArchive true # The ClamAV default
    # ArchiveBlockEncrypted false # The ClamAV default
    # MaxDirectoryRecursion 15 # The ClamAV default
    # FollowDirectorySymlinks false # The ClamAV default
    # FollowFileSymlinks false # The ClamAV default
    # ReadTimeout 180
    # MaxThreads 12
    # MaxConnectionQueueLength 15
    # LogSyslog false # The ClamAV default
    # LogRotate true
    # LogFacility LOG_LOCAL6 # The ClamAV default
    # LogClean false # The ClamAV default
    # LogVerbose false # The ClamAV default
    # DatabaseDirectory /var/lib/clamav
    # OfficialDatabaseOnly false # The ClamAV default
    # SelfCheck 3600
    # Foreground false # The ClamAV default
    # Debug false # The ClamAV default
    # ScanPE true # The ClamAV default
    # MaxEmbeddedPE 10M # The ClamAV default
    # ScanOLE2 true # The ClamAV default
    # ScanPDF true # The ClamAV default
    # ScanHTML true # The ClamAV default
    # MaxHTMLNormalize 10M # The ClamAV default
    # MaxHTMLNoTags 2M # The ClamAV default
    # MaxScriptNormalize 5M # The ClamAV default
    # MaxZipTypeRcg 1M # The ClamAV default
    # ScanSWF true # The ClamAV default
    # DetectBrokenExecutables false # The ClamAV default
    # ExitOnOOM false # The ClamAV default
    # LeaveTemporaryFiles false # The ClamAV default
    # AlgorithmicDetection true # The ClamAV default
    # ScanELF true # The ClamAV default
    # IdleTimeout 30 # The ClamAV default
    # CrossFilesystems true # The ClamAV default
    # PhishingSignatures true # The ClamAV default
    # PhishingScanURLs true # The ClamAV default
    # PhishingAlwaysBlockSSLMismatch false # The ClamAV default
    # PhishingAlwaysBlockCloak false # The ClamAV default
    # PartitionIntersection false # The ClamAV default
    # DetectPUA false # The ClamAV default
    # ScanPartialMessages false # The ClamAV default
    # HeuristicScanPrecedence false # The ClamAV default
    # StructuredDataDetection false # The ClamAV default
    # CommandReadTimeout 5 # The ClamAV default
    # SendBufTimeout 200
    # MaxQueue 100 # The ClamAV default
    # ExtendedDetectionInfo true
    # OLE2BlockMacros false # The ClamAV default
    # ScanOnAccess false # The ClamAV default
    # AllowAllMatchScan true # The ClamAV default
    # ForceToDisk false # The ClamAV default
    # DisableCertCheck false # The ClamAV default
    # DisableCache false # The ClamAV default
    # MaxScanSize 100M # The ClamAV default
    # MaxFileSize 25M # The ClamAV default
    # MaxRecursion 16 # The ClamAV default
    # MaxFiles 10000 # The ClamAV default
    # MaxPartitions 50 # The ClamAV default
    # MaxIconsPE 100 # The ClamAV default
    # PCREMatchLimit 10000 # The ClamAV default
    # PCRERecMatchLimit 5000 # The ClamAV default
    # PCREMaxFileSize 25M # The ClamAV default
    # ScanXMLDOCS true # The ClamAV default
    # ScanHWP3 true # The ClamAV default
    # MaxRecHWP3 16 # The ClamAV default
    # StatsEnabled false # The ClamAV default
    # StatsPEDisabled true # The ClamAV default
    # StatsHostID auto # The ClamAV default
    # StatsTimeout 10 # The ClamAV default
    # StreamMaxLength 25M # The ClamAV default
    # LogFile /var/log/clamav/clamav.log
    # LogTime true
    # LogFileUnlock false # The ClamAV default
    # LogFileMaxSize 0
    # Bytecode true # The ClamAV default
    # BytecodeSecurity TrustSigned # The ClamAV default
    # BytecodeTimeout 60000
    #
    # /etc/clamav/freshclam.conf:
    #
    # # Automatically created by the clamav-freshclam postinst
    # # Comments will get lost when you reconfigure the clamav-freshclam package
    # 
    # DatabaseOwner clamav
    # UpdateLogFile /var/log/clamav/freshclam.log
    # LogVerbose false # The ClamAV default
    # LogSyslog false # The ClamAV default
    # LogFacility LOG_LOCAL6 # The ClamAV default
    # LogFileMaxSize 0
    # LogRotate true
    # LogTime true
    # Foreground false # The ClamAV default
    # Debug false # The ClamAV default
    # MaxAttempts 5
    # DatabaseDirectory /var/lib/clamav # The ClamAV default
    # DNSDatabaseInfo current.cvd.clamav.net # The ClamAV default
    # AllowSupplementaryGroups false # The ClamAV default
    # ConnectTimeout 30
    # ReceiveTimeout 30 # The ClamAV default
    # TestDatabases yes # The ClamAV default
    # ScriptedUpdates yes # The ClamAV default
    # CompressLocalDatabase no # The ClamAV default
    # SafeBrowsing false # The ClamAV default
    # Bytecode true # The ClamAV default
    # NotifyClamd /etc/clamav/clamd.conf
    # # Check for new database 24 times a day
    # Checks 24
    # DatabaseMirror db.local.clamav.net
    # DatabaseMirror database.clamav.net
    #
    # @author Jonathan Hartman <j@p4nt5.com>
    class ClamavConfigDebian < ClamavConfig
      provides :clamav_config, platform_family: 'debian'

      DEFAULTS ||= {
        data_dir: '/var/lib/clamav',
        conf_dir: '/etc/clamav',
        user: 'clamav',
        group: 'clamav',
        clamd_config: {
          bytecode_timeout: 60_000,
          database_directory: '/var/lib/clamav',
          extended_detection_info: true,
          local_socket: '/var/run/clamav/clamd.ctl',
          log_file: '/var/log/clamav/clamav.log',
          log_file_max_size: 0,
          log_rotate: true,
          log_time: true,
          max_connection_queue_length: 15,
          max_threads: 12,
          read_timeout: 180,
          self_check: 3600,
          send_buf_timeout: 200,
          user: 'clamav'
        },
        freshclam_config: {
          checks: 24,
          connect_timeout: 30,
          database_mirror: %w(db.local.clamav.net database.clamav.net),
          database_owner: 'clamav',
          log_file_max_size: 0,
          log_rotate: true,
          log_time: true,
          max_attempts: 5,
          notify_clamd: '/etc/clamav/clamd.conf',
          update_log_file: '/var/log/clamav/freshclam.log'
        }
      }
    end
  end
end
